[package]
name = "guenther"
version = "0.1.0"
authors = ["Kristofers Solo <dev@kristofers.xyz>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = ["bingo"]
bingo = ["dep:image", "dep:noto-sans-mono-bitmap", "dep:sqlx"]
voice-line-capture = []

[dependencies]
async-trait = "0.1"
capitalize = "0.3"
chrono = "0.4"
color-eyre = "0.6"
dotenv = "0.15"
futures = "0.3"
infer = "0.22"
image = { version = "0.25", default-features = false, features = [
  "png",
], optional = true }
noto-sans-mono-bitmap = { version = "0.3", default-features = false, features = [
  "bold",
  "regular",
  "size_16",
  "size_24",
  "size_32",
  "unicode-basic-latin",
  "unicode-latin-1-supplement",
  "unicode-latin-extended-a",
  "unicode-specials",
], optional = true }
rand = "0.10"
regex = "1.12"
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "rustls",
  "stream",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.9", default-features = false, features = [
  "macros",
  "migrate",
  "runtime-tokio",
  "sqlite",
], optional = true }
teloxide = { version = "0.17", default-features = false, features = [
  "ctrlc_handler",
  "macros",
  "rustls",
] }
tempfile = "3"
thiserror = "2.0"
tokio = { version = "1", features = [
  "fs",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "sync",
] }
toml = "1.1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
url = "2.5"

[dev-dependencies]
claims = "0.8"
rstest = "0.26"
temp-env = "0.3"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
# DENY PANICS:
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
