services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUST_FEATURES: ${RUST_FEATURES:-}
    env_file: .env
    environment:
      COBALT_API_URL: http://cobalt:9000/
      ENABLED_PLATFORMS: ${ENABLED_PLATFORMS-instagram,tiktok,twitter,youtube}
    depends_on:
      - cobalt
    restart: unless-stopped
    volumes:
      - ./voice_lines.toml:/app/voice_lines.toml:ro
      - ./comments.txt:/app/comments.txt:ro
  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    restart: unless-stopped
    environment:
      API_URL: http://cobalt:9000/
      CORS_WILDCARD: "0"
