[[voice_lines]]
id = "AgAD-x8AAtQsMVI"
title = "[Achoo]"
file_id = "CQACAgQAAxkBAAMuaca_mmtyAm7fsFs3947T2i1ACVoAAvsfAALULDFSCNd91ikbbyE6BA"
unique_file_id = "AgAD-x8AAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgAD_R8AAtQsMVI"
title = "[errr]"
file_id = "CQACAgQAAxkBAAMvaca_rCWymv3DmpuVDbr8tDtmksAAAv0fAALULDFSE6M9USdqFgI6BA"
unique_file_id = "AgAD_R8AAtQsMVI"
tags = ["guenther", "steiner"]
kind = "audio"

[[voice_lines]]
id = "AgADBiAAAtQsMVI"
title = "Shut Up"
file_id = "CQACAgQAAxkBAAMwaca_t4miBnBot1wYgrxZ0kGOqv0AAgYgAALULDFSE8byYh9IfgI6BA"
unique_file_id = "AgADBiAAAtQsMVI"
tags = ["guenther", "steiner"]
kind = "audio"

[[voice_lines]]
id = "AgADCCAAAtQsMVI"
title = "Super Max"
file_id = "CQACAgQAAxkBAAMxaca_t6xwJhENCGCq35GTCJfA0kkAAgggAALULDFSjc5ttmQ4M0k6BA"
unique_file_id = "AgADCCAAAtQsMVI"
tags = ["guenther", "steiner"]
kind = "audio"

[[voice_lines]]
id = "AgADCiAAAtQsMVI"
title = "There's something lose between my legs"
file_id = "CQACAgQAAxkBAAMyaca_t2cTWUm2b33wUNq_HHuP_c8AAgogAALULDFSh4mFPmq0hgg6BA"
unique_file_id = "AgADCiAAAtQsMVI"
tags = ["vettel"]
kind = "audio"

[[voice_lines]]
id = "AgADCSAAAtQsMVI"
title = "We Look Like a Bunch of Wankers"
file_id = "CQACAgQAAxkBAAMzaca_tyeXl_zXgmUvR_n0xpOYZYsAAgkgAALULDFSvKdE4uKa0VI6BA"
unique_file_id = "AgADCSAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADCyAAAtQsMVI"
title = "Who let the dogs out"
file_id = "CQACAgQAAxkBAAM0aca_t8qzlnUtLZlI7lSVTuTw558AAgsgAALULDFSjwUYaLZtsfw6BA"
unique_file_id = "AgADCyAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADDCAAAtQsMVI"
title = "**** Raikkonen"
file_id = "CQACAgQAAxkBAAM1aca_tzwsx5DTYNM8uQLCKP0tnNYAAgwgAALULDFSXlROy4D8_OM6BA"
unique_file_id = "AgADDCAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgAD_h8AAtQsMVI"
title = "And now we are fucking bunch of wankers"
file_id = "CQACAgQAAxkBAAM2aca_t6lJig3i_i9fveLLW09dKJMAAv4fAALULDFSd8HqCQjhx5E6BA"
unique_file_id = "AgAD_h8AAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgAD_x8AAtQsMVI"
title = "Devries behind"
file_id = "CQACAgQAAxkBAAM3aca_t4vWLWdHZC6B5ucyHBIBNEsAAv8fAALULDFSv7hPNLQ8kiA6BA"
unique_file_id = "AgAD_x8AAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADAyAAAtQsMVI"
title = "Face to face with a Godzilla"
file_id = "CQACAgQAAxkBAAM4aca_tynOGvAjAuC_22PywqCOD_MAAgMgAALULDFSPDueMW0F8kY6BA"
unique_file_id = "AgADAyAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADASAAAtQsMVI"
title = "I am stupid"
file_id = "CQACAgQAAxkBAAM5aca_t0wRibgaR5A48fsBJ_RqtO8AAgEgAALULDFS9ZmefdCFVww6BA"
unique_file_id = "AgADASAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgAEIAAC1CwxUg"
title = "I was shitting myself"
file_id = "CQACAgQAAxkBAAM6aca_t1A6wCYcVaLS0J97Yhhz6C0AAyAAAtQsMVKp8v_eSDzfAzoE"
unique_file_id = "AgAEIAAC1CwxUg"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADAiAAAtQsMVI"
title = "In in in in in"
file_id = "CQACAgQAAxkBAAM7aca_t1V_EJ3B8fB7Dv6JZ1lhn-MAAgIgAALULDFSpTrwWVdgkiQ6BA"
unique_file_id = "AgADAiAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADBCAAAtQsMVI"
title = "It's one short word - shit"
file_id = "CQACAgQAAxkBAAM8aca_t6lrjSMO-I6RGGq5CiSAyIMAAgQgAALULDFSmuRTYfw-O2s6BA"
unique_file_id = "AgADBCAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADBSAAAtQsMVI"
title = "Max Verstappen"
file_id = "CQACAgQAAxkBAAM9aca_t3u6mYdlSwnKcetu7T1B5_wAAgUgAALULDFSOCOLiwO879A6BA"
unique_file_id = "AgADBSAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADDSAAAtQsMVI"
title = "Mercedes Petronas F1 Team anthem"
file_id = "CQACAgQAAxkBAAM-aca_twIiIyaTe3uoJcaMMXkOy54AAg0gAALULDFS-1HUcT5z8Nc6BA"
unique_file_id = "AgADDSAAAtQsMVI"
tags = []
kind = "audio"

[[voice_lines]]
id = "AgADByAAAtQsMVI"
title = "No, fock off!"
file_id = "CQACAgQAAxkBAAM_aca_ty5c-4Ve9kMg80xQROaYzvQAAgcgAALULDFS_Hk7JqceCu06BA"
unique_file_id = "AgADByAAAtQsMVI"
tags = []
kind = "audio"
